### ISSUE TITLE
unexpected error popped up

### ISSUE THREAD

**Issue by WXZhao7** [microsoft/vscode-isort#129]
When I code at **interactive window**, the error message popped up.
![image](https://user-images.githubusercontent.com/56864878/197105976-b0cc6479-df6f-4195-bc5e-557d21fe0bb9.png)

## setting
```json
    "isort.logLevel": "warn",
    "isort.severity": {
        "W": "Information",
        "E": "Warning"
    },
    "isort.showNotifications": "onError",
    "isort.check": true
```
### example1
type
```python
import numpy as np
??np.nan
```
output
```
[Error - 11:34:07 AM] Syntax error in code: Traceback (most recent call last):
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/tool/server.py", line 273, in is_python
    ast.parse(code)
  File "/home/wxz/Program/miniconda3/envs/seismic/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2
    ??np.nan
    ^
SyntaxError: invalid syntax

[Warn  - 11:34:07 AM] Skipping non python code: Interactive-1.interactive
```
### example2
type `!ls`
output
```
[Warn  - 11:37:01 AM] Skipping non python code: Interactive-1.interactive
[Error - 11:38:43 AM] Syntax error in code: Traceback (most recent call last):
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/tool/server.py", line 273, in is_python
    ast.parse(code)
  File "/home/wxz/Program/miniconda3/envs/seismic/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    !ls
    ^
SyntaxError: invalid syntax

[Warn  - 11:38:43 AM] Skipping non python code: Interactive-1.interactive
```
### extra, unexpected UnboundLocalError?  
type `import numpy as np`
output
```
/home/wxz/Program/miniconda3/envs/seismic/bin/python -m isort - --profile black --check --filename Interactive-1.interactive
CWD Linter: /home/wxz/Work/MoXi/noise/NoiseCorr
[Warn  - 11:39:59 AM] Traceback (most recent call last):
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/tool/server.py", line 556, in _run_tool_on_document
    result = utils.run_module(
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/tool/utils.py", line 141, in run_module
    return _run_module(module, argv, use_stdin, source)
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/tool/utils.py", line 126, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "/home/wxz/Program/miniconda3/envs/seismic/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/wxz/Program/miniconda3/envs/seismic/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/libs/isort/__main__.py", line 3, in <module>
    main()
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/libs/isort/main.py", line 1119, in main
    incorrectly_sorted = not api.check_stream(
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/libs/isort/api.py", line 264, in check_stream
    changed: bool = sort_stream(
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/libs/isort/api.py", line 189, in sort_stream
    raise FileSkipSetting(content_source)
isort.exceptions.FileSkipSetting: Interactive-1.interactive was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting

[Error - 11:39:59 AM] isort check failed with error:
Traceback (most recent call last):
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/tool/server.py", line 100, in _linting_helper
    result = _run_tool_on_document(document, use_stdin=True, extra_args=["--check"])
  File "/home/wxz/.vscode/extensions/ms-python.isort-2022.3.12931038/bundled/tool/server.py", line 569, in _run_tool_on_document
    if result.stderr:
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by karthiknadig** [comment]
@WXZhao7 I recommend removing the `showNotification` setting. Pylance language server should be able to detect any syntax errors. and Any Import organization errors here you can always look at the logs.

@luabud This happens because user has `showNotification` on error and there was a python syntax error. There are two options, 1) not trigger notification for syntax errors 2) skip organize imports in interactive window.

I would go for 2. what do you suggest?

**Comment by WXZhao7** [comment]
@karthiknadig I agree with you. I think interactive window do not need sort imports.

**Comment by WXZhao7** [comment]
@karthiknadig I agree with you. I think interactive window do not need sort imports.
