### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-isort#18]
Testing microsoft/vscode-python#18997

I don't think I did anything really, maybe I clicked on the error shown in the editor:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/5047891/165338310-60820b3d-d133-4454-93bf-60bcbe673a4e.png">

```
ERR Cannot read properties of null (reading 'map'): TypeError: Cannot read properties of null (reading 'map')
	at g (c:\Users\alex\.vscode\extensions\ms-python.isort-2022.1.11161003\dist\extension.js:1:212940)
	at Object.asCodeAction (c:\Users\alex\.vscode\extensions\ms-python.isort-2022.1.11161003\dist\extension.js:1:223880)
	at c:\Users\alex\.vscode\extensions\ms-python.isort-2022.1.11161003\dist\extension.js:1:152614
	at async U.provideCodeActions (c:\Users\alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:100925)
```

**Comment by karthiknadig** [comment]
`asCodeAction` is called inside LS Client library. I am suspecting we were returning null for code action when we should be returning something. I am hoping that addressing #15 should also address this.
