### ISSUE TITLE
isort extension crashes when scoped `source.organzeImports` action is present

### ISSUE THREAD

**Issue by charliermarsh** [microsoft/vscode-isort#192]
:wave: I'm trying to add a `source.organizeImports.ruff` action to the [Ruff extension](https://github.com/charliermarsh/ruff-vscode). The goal is to enable users who have the `isort` extension installed to opt-in to sorting imports with Ruff instead, like this:

```json
{
    "[python]": {
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports.ruff": true
        }
    }
}
```

However, when the `isort` extension is installed, this configuration causes the `isort` extension to crash repeatedly, and impedes the Ruff extension's import sorting somehow. (If I uninstall the `isort` extension, the Ruff extension works as expected.)

(This started with an issue in the Ruff extension repo: https://github.com/charliermarsh/ruff-vscode/issues/76. The use of provider-scoped `source.organizeImports` was inspired by what I've seen with the ESLint extension, and in this issue: https://github.com/microsoft/vscode/issues/90221.)

**Comment by brettcannon** [comment]
Do you have any logs for the crash of the isort extension?

**Comment by karthiknadig** [comment]
This is the traceback for the error:
```
Traceback (most recent call last):
  File "c:\GIT\formatters\vscode-isort\bundled\libs\pygls\protocol.py", line 152, in deserialize_message
    deserialize_params(data, get_params_type)
  File "c:\GIT\formatters\vscode-isort\bundled\libs\pygls\protocol.py", line 138, in deserialize_params
    data['params'] = params_type(**params)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "c:\GIT\formatters\vscode-isort\bundled\libs\pygls\lsp\types\basic_structures.py", line 58, in __init__
    super().__init__(**data)
  File "c:\GIT\formatters\vscode-isort\bundled\libs\pydantic\main.py", line 342, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for CodeActionParams
context -> only -> 0
  value is not a valid enumeration member; permitted: '', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports' (type=type_error.enum; enum_values=[<CodeActionKind.Empty: ''>, <CodeActionKind.QuickFix: 'quickfix'>, <CodeActionKind.Refactor: 'refactor'>, <CodeActionKind.RefactorExtract: 'refactor.extract'>, <CodeActionKind.RefactorInline: 'refactor.inline'>, <CodeActionKind.RefactorRewrite: 'refactor.rewrite'>, <CodeActionKind.Source: 'source'>, <CodeActionKind.SourceOrganizeImports: 'source.organizeImports'>])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\GIT\formatters\vscode-isort\bundled\libs\pygls\protocol.py", line 452, in data_received
    self._data_received(data)
  File "c:\GIT\formatters\vscode-isort\bundled\libs\pygls\protocol.py", line 484, in _data_received
    json.loads(body.decode(self.CHARSET),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\GIT\formatters\vscode-isort\bundled\libs\pygls\protocol.py", line 154, in deserialize_message
    raise JsonRpcInvalidParams()
pygls.exceptions.JsonRpcInvalidParams: Invalid Params
```

this is due to a bug in `pygls` where it was using `pydantic`. The latest version of `pygls` uses `lsprotocol` which does not have this problem. `lsprotocol` is more flexible with code actions.

**Comment by karthiknadig** [comment]
The fix here is to update `isort` extension to use `pygls` with `lsprotocol`. This will require some minor code changes in `server.py`. 

@charliermarsh you may wat to upgrade `pygls` as well, and make similar changes to `server.py` as i will have in the fix for this.

**Comment by charliermarsh** [comment]
Thank you! (And sorry -- I did _not_ have a trace handy, then meant to come back to this but got distracted.)

@karthiknadig - If it's helpful, I actually did the pygls upgrade a few weeks ago for Ruff: https://github.com/charliermarsh/ruff-vscode/pull/37.

**Comment by karthiknadig** [comment]
@charliermarsh perfect.
