### ISSUE TITLE
Couldn't start client isort

### ISSUE THREAD

**Issue by msetGMN** [microsoft/vscode-isort#199]
Since a few days when I start VS Code I get the notification saying "couldn't start client isort - Source: isort (Extension)
I tried to uninstall und reinstall the extension but nothing changed. 
I also tried to install older versions and reloaded VS Code, this also didn't help my issue. 

Can somebody help and tell me what to do?

**Comment by karthiknadig** [comment]
@msetGMN Can you share logs from Output > isort ? Also, Help > toggle developer tools, and looks for any errors there.

**Comment by jplindquist** [comment]
I've noticed something recently too with plugin / server failing to start (also happening with the Black extension as well fwiw with similar errors)

```
The isort server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

with the following in the console output tab

```
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotationsi
    ^
SyntaxError: future feature annotationsi is not defined
[Info  - 9:22:20 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotationsi
    ^
SyntaxError: future feature annotationsi is not defined
[Info  - 9:22:20 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotationsi
    ^
SyntaxError: future feature annotationsi is not defined
[Info  - 9:22:20 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotationsi
    ^
SyntaxError: future feature annotationsi is not defined
[Info  - 9:22:20 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotationsi
    ^
SyntaxError: future feature annotationsi is not defined
[Error - 9:22:20 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by karthiknadig** [comment]
@jplindquist something doesn't seem right here.
```
[Info  - 9:22:20 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotationsi
    ^
SyntaxError: future feature annotationsi is not defined
```
That error either means the version of python used is less than 3.7 or that `server.py` is corrupt. Because, `server.py` contains `from __future__ import annotations` without the `i` in the end.

**Comment by jplindquist** [comment]
I think that was just a typo or copy fail on my part when I was editing the comment 🤦 It's running under python 3.11.1 packaged from homebrew I believe and I've removed/reinstalled it a few times and tried downgrading versions

**Comment by karthiknadig** [comment]
Can you share the full log from Output > isort? The error you mention above is only possible if the python being used in 3.6 or lower, or if the install for 3.11 for some reason was corrupted.

**Comment by jplindquist** [comment]
This is the full output from Output > isort after triggering `isort Formatter: Restart Server` from the command palette. 

```
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:13 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:13 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:13 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Info  - 1:44:13 PM] Connection to server got closed. Server will restart.
  File "/Users/jlindquist/.vscode/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[Error - 1:44:13 PM] Connection to server got closed. Server will not be restarted.
```

![image](https://user-images.githubusercontent.com/5132333/213291099-92e43e4a-a7e6-41b3-a80e-4c7e40f21152.png)


> python -V
Python 3.11.1

**Comment by karthiknadig** [comment]
@jplindquist Can you share the Output > Python logs?

**Comment by jplindquist** [comment]
🤦 again! I think you helped me figure this out, thank you!  I had to run `Python: Clear Cache and Reload Window` because it was somehow using Python 3.6.15 or so that I had installed from Pyenv, and Python 3.11 is supposed to be the default for the env

This is what it shows now, but prior to this I could see it trying multiple languages that I have installed from pyenv and failing
```
Experiment 'pythonaacf' is active
Experiment 'pythonPromptNewToolsExt' is active
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
Python interpreter path: ~/.pyenv/versions/3.11.1/bin/python
Starting Pylance language server.
```

Thank you!  I'm all good here

**Comment by kkibria** [comment]
I have a similar problem, this is what I am getting starting from yesterday,
```
2024-02-17 13:15:16.240 [info] [Error - 1:15:16 PM] Restarting server failed
2024-02-17 13:15:16.240 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-02-17 13:15:17.042 [info] Traceback (most recent call last):
  File "c:\Users\User1\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 42, in <module>
    from pygls import server, uris, workspace
  File "c:\Users\User1\.vscode\extensions\ms-python.isort-2023.10.1\bundled\libs\pygls\server.py", line 17, in <module>

2024-02-17 13:15:17.042 [info]     import asyncio
  File "asyncio\__init__.py", line 8, in <module>
  File "asyncio\base_events.py", line 23, in <module>
  File "socket.py", line 51, in <module>

2024-02-17 13:15:17.044 [info] ModuleNotFoundError: No module named '_socket'

2024-02-17 13:15:17.111 [info] [Error - 1:15:17 PM] Server initialization failed.
2024-02-17 13:15:17.111 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-02-17 13:15:17.111 [info] [Error - 1:15:17 PM] The isort server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-02-17 13:15:17.111 [info] [Error - 1:15:17 PM] isort client: couldn't create connection to server.
2024-02-17 13:15:17.111 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-02-17 13:15:17.112 [info] [Error - 1:15:17 PM] Restarting server failed
2024-02-17 13:15:17.112 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```
>python -V
>Python 3.10.2

**Comment by Sandman6z** [comment]
So I meet this question again.

---

```
2026-05-13 10:15:28.722 [info] [Error - 10:15:28] Server process exited with code 1.
2026-05-13 10:15:28.728 [info] [Error - 10:15:28] Server initialization failed.
2026-05-13 10:15:28.728 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2026-05-13 10:15:28.728 [info] [Info  - 10:15:28] Connection to server got closed. Server will restart.
2026-05-13 10:15:28.728 [info] true
2026-05-13 10:15:28.728 [info] [Error - 10:15:28] isort client: couldn't create connection to server.
2026-05-13 10:15:28.728 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2026-05-13 10:15:28.728 [info] [Error - 10:15:28] Restarting server failed
2026-05-13 10:15:28.728 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2026-05-13 10:15:29.956 [info] Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\importlib\metadata\__init__.py", line 407, in from_name
    return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\boe\.vscode\extensions\ms-python.isort-2026.4.0\bundled\tool\lsp_server.py", line 65, in <module>
    import isort
  File "c:\Users\boe\.vscode\extensions\ms-python.isort-2026.4.0\bundled\libs\isort\__init__.py", line 23, in <module>
    from ._version import __version__
  File "c:\Users\boe\.vscode\extensions\ms-python.isort-2026.4.0\bundled\libs\isort\_version.py", line 3, in <module>
    __version__ = metadata.version("isort")
  File "C:\Program Files\Python313\Lib\importlib\metadata\__init__.py", line 987, in version
    return distribution(distribution_name).version
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\importlib\metadata\__init__.py", line 960, in distribution
    return Distribution.from_name(distribution_name)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\importlib\metadata\__init__.py", line 409, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for isort

2026-05-13 10:15:29.958 [info] [Error - 10:15:29] Server process exited with code 1.
2026-05-13 10:15:29.984 [info] [Error - 10:15:29] Server initialization failed.
2026-05-13 10:15:29.984 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2026-05-13 10:15:29.984 [info] [Error - 10:15:29] The isort server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2026-05-13 10:15:29.985 [info] [Error - 10:15:29] isort client: couldn't create connection to server.
2026-05-13 10:15:29.985 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2026-05-13 10:15:29.986 [info] [Error - 10:15:29] Restarting server failed
2026-05-13 10:15:29.986 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```
