### ISSUE TITLE
"TypeError: (u ?? []).map is not a function" in extension host logs

### ISSUE THREAD

**Issue by KholdStare** [microsoft/vscode-isort#206]
The new isort plugin does not work at all for me. In Remote Extension Host output:

```
2023-01-20 18:07:12.712 [error] TypeError: (u ?? []).map is not a function
	at c (/home/kholdstare/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:7427)
	at t.restartServer (/home/kholdstare/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:5603)
	at g (/home/kholdstare/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:311987)
	at /home/kholdstare/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:312541
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

My workspace config:
```
{
  "folders": [
    {
      "path": "backend/python/lib/uflow"
    }
  ],
  "settings": {
    "[python]": {
      "editor.tabSize": 4,
      "editor.formatOnSave": true,
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      }
    },
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.pylintPath": "pylint",
    "python.linting.lintOnSave": true,
    "python.formatting.provider": "black",
    "python.linting.mypyEnabled": true,
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python",
    "isort.interpreter": "${workspaceFolder}/.venv/bin/python",
    "isort.args": [
      "--settings-path", "${workspaceFolder}/.isort.cfg",
    ]
    "python.linting.mypyArgs": [
      "--config-file", "${workspaceFolder}/.mypy.ini"
    ],
    "python.poetryPath": "~/.local/bin/poetry",
    "yaml.schemas": {
      "https://json.schemastore.org/github-workflow.json": ".github/workflows/build.yml"
    },
  }
}
```

My isort config:

```
[isort]
profile = black
```

isort works perfectly fine if I revert to `ms-python.python` `v2022.16.1` and uninstall the dedicated `ms-python.isort` extension

**Comment by karthiknadig** [comment]
@KholdStare Your setting here is wrong:
```
"isort.interpreter": "${workspaceFolder}/.venv/bin/python"
```
it has to be an array:
```
"isort.interpreter": ["${workspaceFolder}/.venv/bin/python"]
```

**Comment by karthiknadig** [comment]
Also, you don't have to set that if you have selected it as the python for your workspace from the python extension.

**Comment by KholdStare** [comment]
Thanks, I will give it a try.

> Also, you don't have to set that if you have selected it as the python for your workspace from the python extension.

If I don't set the isort.interpreter I get 

```
[ERROR 2023-0-20 19:0:0.822]: Python interpreter missing:
[Option 1] Select python interpreter using the ms-python.python.
[Option 2] Set an interpreter using "isort.interpreter" setting.
```

Even though everything else works perfectly fine in the python extension itself

**Comment by karthiknadig** [comment]
@KholdStare Did setting it to an array address the issue?

**Comment by KholdStare** [comment]
@karthiknadig Yes, specifying it as an array fixed the `TypeError` issue, thanks
