### ISSUE TITLE
 ERR_INVALID_ARG_TYPE on pre-release (v2023.9.10371012)

### ISSUE THREAD

**Issue by markedwards** [microsoft/vscode-isort#238]
The pre-release (v2023.9.10371012) build of vscode-isort stopped working yesterday, with this error in Output -> isort:
```
undefined 
CWD: /cargo/api
[ERROR 2023-1-10 8:2:53.364]: [TypeError: The "file" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at validateString (node:internal/validators:120:11)
	at normalizeSpawnArguments (node:child_process:505:3)
	at spawn (node:child_process:693:13)
	at Object.execFile (node:child_process:327:17)
	at /home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:71194
	at new Promise (<anonymous>)
	at l (/home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:71163)
	at t.textEditRunner (/home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:73253)
	at async u.resolveCodeAction (/home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:78965)
	at async V.resolveCodeAction (/home/gidev/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/workbench/api/node/extensionHostProcess.js:98:38557)] {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by karthiknadig** [comment]
Can you share the entire Log after setting `"isort.logLevel": "debug"`? and your settings?

**Comment by markedwards** [comment]
This is the log after setting `"isort.logLevel": "debug"`:
```
Name: isort
Module: isort
[DEBUG 2023-1-13 8:35:54.181]: Configuration: {"name":"isort","module":"isort"}
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
undefined 
CWD: /cargo/api
[ERROR 2023-1-13 8:36:0.159]: [TypeError: The "file" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at validateString (node:internal/validators:120:11)
	at normalizeSpawnArguments (node:child_process:505:3)
	at spawn (node:child_process:693:13)
	at Object.execFile (node:child_process:327:17)
	at /home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:71194
	at new Promise (<anonymous>)
	at l (/home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:71163)
	at t.textEditRunner (/home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:73253)
	at async u.resolveCodeAction (/home/gidev/.vscode-server/extensions/ms-python.isort-2023.9.10371012/dist/extension.js:1:78965)
	at async V.resolveCodeAction (/home/gidev/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/workbench/api/node/extensionHostProcess.js:98:38557)] {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

settings on the remote container (where this is running) are:
```
{
	"isort.logLevel": "debug",
	"isort.serverEnabled": false
}
```

Do you want to see settings elsewhere?  The extension was working fine, and then I think an update to VSCode caused this issue to start occurring.  I don't think it was triggered by an isort extension update.

**Comment by markedwards** [comment]
My VSCode version info:
```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:01.965Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

**Comment by karthiknadig** [comment]
This means that a `python` has not been selected. It should handle that case better.

**Comment by markedwards** [comment]
VSCode does know about the python in my dev container, and other things like flake8 and mypy work as expected.  Pylance is working as expected.

Are you saying that there's something misconfigured on my end?  Or that there's some issue in the pre-release of the isort extension?

**Comment by karthiknadig** [comment]
@markedwards isort is not picking up the right python. As a workaround you can set `"isort.interpreter":["<path to python>"]`.

**Comment by markedwards** [comment]
I set this and I still get the same error:
```
{
	"isort.interpreter": ["/usr/local/bin/python"],
	"isort.serverEnabled": false
}
```

**Comment by karthiknadig** [comment]
This is a regression. Will look into it.

**Comment by markedwards** [comment]
Ah, I see that I was wrong above about a VSCode update causing this.  For some reason I thought I started seeing this bug using the build you provided on #163.  But I was mistaken, I think the VSCode update blew away that build and I never actually confirmed that.

I've reinstalled the build from #163 and I can confirm that is working fine.  So it is indeed something that changed in the isort extension.

**Comment by Yoshi325** [comment]
vscode-isort release (v2022.8.0) and pre-release (v2023.9.10371012) were conflicting with [esbonio](https://pypi.org/project/esbonio/). It vaguely looked like something to do with the language server, so after looking for Issues, I decided to try the latest code (827f5576f51c6da9034e27bfb287b3b2018e9359). I built and manually installed the vsix. Setting `serverEnabled` to false produced the same error as markedwards reported above. And as expected, the workaround (manually setting the interpreter) does not work for me as well (same error). Good news is that setting `serverEnabled` to true when running the latest solves for my usecase (it even resolves the correct interpreter without requiring the setting for what that is worth). So ultimately I guess this is a long-winded `+1` to this Issue, but maybe it will be helpful to someone.

**Comment by karthiknadig** [comment]
This should be fixed in pre-release `2023.9.10451716`

**Comment by Yoshi325** [comment]
confirmed for me, v2023.9.10451716 with `serverEnabled` set to False works! (including with esbonio) thank you!! (even though I'm not the original poster)

**Comment by markedwards** [comment]
Also confirmed fixed.  Thanks @karthiknadig.
