### ISSUE TITLE
The isort server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

### ISSUE THREAD

**Issue by q447552640** [microsoft/vscode-isort#316]
2023-08-19 01:13:09.305 [info] Name: isort
2023-08-19 01:13:09.305 [info] Module: isort
2023-08-19 01:13:09.305 [info] Python extension loading
2023-08-19 01:13:09.305 [info] Waiting for interpreter from python extension.
2023-08-19 01:13:09.305 [info] No interpreter found from setting isort.interpreter
2023-08-19 01:13:09.305 [info] Getting interpreter from ms-python.python extension for workspace d:\work\njbdbd\dreamface\DreamSpaceLiveStream
2023-08-19 01:13:09.305 [info] Python extension loaded
2023-08-19 01:13:09.305 [info] Interpreter from ms-python.python extension for d:\work\njbdbd\dreamface\DreamSpaceLiveStream: d:\work\njbdbd\dreamface\python39\python.exe
2023-08-19 01:13:09.305 [info] No interpreter found from setting isort.interpreter
2023-08-19 01:13:09.328 [info] Getting interpreter from ms-python.python extension for workspace d:\work\njbdbd\dreamface\DreamSpaceLiveStream
2023-08-19 01:13:09.328 [info] Interpreter from ms-python.python extension for d:\work\njbdbd\dreamface\DreamSpaceLiveStream: d:\work\njbdbd\dreamface\python39\python.exe
2023-08-19 01:13:09.328 [info] Server run command: d:\work\njbdbd\dreamface\python39\python.exe c:\Users\admin\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py
2023-08-19 01:13:09.328 [info] Server: Start requested.
2023-08-19 01:13:10.526 [info] Traceback (most recent call last):
  File "c:\Users\admin\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 39, in <module>
    import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-08-19 01:13:10.556 [info] [Error - 01:13:10] Server initialization failed.
2023-08-19 01:13:10.556 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:10.557 [info] [Info  - 01:13:10] Connection to server got closed. Server will restart.
2023-08-19 01:13:10.557 [info] true
2023-08-19 01:13:10.557 [info] [Error - 01:13:10] isort client: couldn't create connection to server.
2023-08-19 01:13:10.557 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:11.168 [info] Traceback (most recent call last):
  File "c:\Users\admin\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 39, in <module>

2023-08-19 01:13:11.169 [info]     import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-08-19 01:13:13.769 [info] [Error - 01:13:13] Server initialization failed.
2023-08-19 01:13:13.770 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:13.770 [info] [Info  - 01:13:13] Connection to server got closed. Server will restart.
2023-08-19 01:13:13.770 [info] true
2023-08-19 01:13:13.770 [info] [Error - 01:13:13] isort client: couldn't create connection to server.
2023-08-19 01:13:13.770 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:13.770 [error] Server: Start failed: Error: Pending response rejected since connection got disposed
2023-08-19 01:13:14.365 [info] Traceback (most recent call last):
  File "c:\Users\admin\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 39, in <module>
    import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-08-19 01:13:14.386 [info] [Error - 01:13:14] Server initialization failed.
2023-08-19 01:13:14.386 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:14.386 [info] [Info  - 01:13:14] Connection to server got closed. Server will restart.
2023-08-19 01:13:14.386 [info] true
2023-08-19 01:13:14.386 [info] [Error - 01:13:14] isort client: couldn't create connection to server.
2023-08-19 01:13:14.386 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:14.387 [info] [Error - 01:13:14] Restarting server failed
2023-08-19 01:13:14.387 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:15.303 [info] Traceback (most recent call last):
  File "c:\Users\admin\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 39, in <module>
    import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-08-19 01:13:15.331 [info] [Error - 01:13:15] Server initialization failed.
2023-08-19 01:13:15.331 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:15.332 [info] [Info  - 01:13:15] Connection to server got closed. Server will restart.
2023-08-19 01:13:15.332 [info] true
2023-08-19 01:13:15.332 [info] [Error - 01:13:15] isort client: couldn't create connection to server.
2023-08-19 01:13:15.332 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:15.332 [info] [Error - 01:13:15] Restarting server failed
2023-08-19 01:13:15.332 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:15.799 [info] Traceback (most recent call last):
  File "c:\Users\admin\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 39, in <module>
    import lsp_jsonrpc as jsonrpc
ModuleNotFoundError: No module named 'lsp_jsonrpc'

2023-08-19 01:13:15.803 [info] [Error - 01:13:15] Server initialization failed.
2023-08-19 01:13:15.803 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:15.803 [info] [Error - 01:13:15] The isort server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-08-19 01:13:15.803 [info] [Error - 01:13:15] isort client: couldn't create connection to server.
2023-08-19 01:13:15.803 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-19 01:13:15.803 [info] [Error - 01:13:15] Restarting server failed
2023-08-19 01:13:15.803 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by karthiknadig** [comment]
Can you run `dir` on this directory to ensure that it has all the needed files?
`c:\Users\admin.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\`

Are you using any custom encoding in your OS?

**Comment by karthiknadig** [comment]
This seems to be the case for embedded/portable python. I am open for a PR adding the changes that were done for black to address this.

**Comment by Column01** [comment]
Also having this issue, the bundled install doesn't find the modules needed. Do not want to install them to my venv for the project either

**Comment by karthiknadig** [comment]
@MiltiadisKoutsokeras If you are not using portable python then make sure the following directory exists in the extension. 
`<HOME>/.vscode-oss/extensions/ms-python.isort-2023.10.1-universal/bundled/lib`. If it is not present then the OSS version of the extension build is broken.

**Comment by karthiknadig** [comment]
@MiltiadisKoutsokeras This issue is with how the package was created by whoever uploaded to the VSCodium's extension store. If you download the VSIX from the VS Code store you will see that it exists. Please raise an issue on the there. There is nothing we can do here.

**Comment by nriley** [comment]
I am having this problem with the official MS release of VSCode on Windows and the official VSCode store, not using VSCodium.

The problem as [others have identified](https://github.com/microsoft/vscode-isort/issues/316#issuecomment-1715653138) seems to be that the directory `bundled\tool` is not in the Python path. 

I am using a portable Python as I am not an administrator on this computer and cannot install Python for the system. Here's what PYTHONPATH looks like prior to me doing this.

```python
['c:\\Users\\nriley\\.vscode\\extensions\\ms-python.isort-2023.13.10681007\\bundled\\libs',
'',
'C:\\Users\\nriley\\Apps\\Python\\python311.zip',
'C:\\Users\\nriley\\Apps\\Python',
'C:\\Users\\nriley\\Apps\\Python\\Lib\\site-packages',
'C:\\Users\\nriley\\Apps\\Python\\Lib\\site-packages\\win32',
'C:\\Users\\nriley\\Apps\\Python\\Lib\\site-packages\\win32\\lib',
'C:\\Users\\nriley\\AppData\\Roaming\\Python\\venv\\3.11',
'C:\\Users\\nriley\\AppData\\Roaming\\Python\\venv\\3.11\\Lib\\site-packages']
```

Copying the following lines from the linked vscode-black commit and adding them to lsp_server.py fixed the issue:

```python
BUNDLE_DIR = pathlib.Path(__file__).parent.parent
# Always use bundled server files.
update_sys_path(os.fspath(BUNDLE_DIR / "tool"), "useBundled")

```

Unfortunately I do not have time to submit a PR right now but did not want to get this lost, as I was somewhat confused reading this issue that the original reported problem is still a problem with a known solution and just awaiting a PR to fix.

**Comment by Sl0m** [comment]
HI, I'm not sure if I should create a new issue or comment here but for a few days I've gotten this issue.
```
2026-05-05 10:00:20.912 [info] Server run command: /home/$USER/project/.venv/bin/python /home/$USER/.vscode/extensions/ms-python.isort-2026.4.0/bundled/tool/lsp_server.py
2026-05-05 10:00:20.913 [info] Server: Start requested.
2026-05-05 10:00:21.281 [info] Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/$USER/.vscode/extensions/ms-python.isort-2026.4.0/bundled/tool/lsp_server.py", line 65, in <module>
    import isort
  File "/home/$USER/.vscode/extensions/ms-python.isort-2026.4.0/bundled/libs/isort/__init__.py", line 23, in <module>
    from ._version import __version__
  File "/home/$USER/.vscode/extensions/ms-python.isort-2026.4.0/bundled/libs/isort/_version.py", line 3, in <module>
    __version__ = metadata.version("isort")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 889, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for isort

2026-05-05 10:00:21.299 [info] [Error - 10:00:21 AM] Server process exited with code 1.
2026-05-05 10:00:21.373 [info] [Error - 10:00:21 AM] Server initialization failed.

[...]

2026-05-05 10:00:23.225 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2026-05-05 10:00:23.225 [info] [Error - 10:00:23 AM] The isort server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

I do have this folder:
`~/.vscode/extensions/ms-python.isort-2026.4.0/bundled/libs/`

And here is my vscode version:
`➜  ~ code --version 
1.116.0
560a9dba96f961efea7b1612916f89e5d5d4d679
x64
`

And he is the OS i'm running one: `Ubuntu 24.04.4 LTS`

If you need more infos, just tell me ! 

And I hope whoever is reading this is having a good day :)

**Comment by gullevek** [comment]
Since updating to 1.120.0 I have the same problem.

```
1.120.0
0958016b2af9f09bb4257e0df4a95e2f90590f9f
x64
```

I could fix it on my local machine (macOS) by pointing it to a python installed from MacPorts, but on my remote connections, setting it to the OS python (3.13) does not fix the problem

It will throw the same error

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
    return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clemens/.vscode-server/extensions/ms-python.isort-2026.4.0/bundled/tool/lsp_server.py", line 65, in <module>
    import isort
  File "/home/clemens/.vscode-server/extensions/ms-python.isort-2026.4.0/bundled/libs/isort/__init__.py", line 23, in <module>
    from ._version import __version__
  File "/home/clemens/.vscode-server/extensions/ms-python.isort-2026.4.0/bundled/libs/isort/_version.py", line 3, in <module>
    __version__ = metadata.version("isort")
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 987, in version
    return distribution(distribution_name).version
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
    return Distribution.from_name(distribution_name)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for isort
```
