### ISSUE TITLE
Couldn't start client isort, asyncio failing

### ISSUE THREAD

**Issue by kkibria** [microsoft/vscode-isort#387]
I have a similar problem, this is what I am getting starting from yesterday,
```
2024-02-17 13:15:16.240 [info] [Error - 1:15:16 PM] Restarting server failed
2024-02-17 13:15:16.240 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-02-17 13:15:17.042 [info] Traceback (most recent call last):
  File "c:\Users\User1\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 42, in <module>
    from pygls import server, uris, workspace
  File "c:\Users\User1\.vscode\extensions\ms-python.isort-2023.10.1\bundled\libs\pygls\server.py", line 17, in <module>

2024-02-17 13:15:17.042 [info]     import asyncio
  File "asyncio\__init__.py", line 8, in <module>
  File "asyncio\base_events.py", line 23, in <module>
  File "socket.py", line 51, in <module>

2024-02-17 13:15:17.044 [info] ModuleNotFoundError: No module named '_socket'

2024-02-17 13:15:17.111 [info] [Error - 1:15:17 PM] Server initialization failed.
2024-02-17 13:15:17.111 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-02-17 13:15:17.111 [info] [Error - 1:15:17 PM] The isort server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-02-17 13:15:17.111 [info] [Error - 1:15:17 PM] isort client: couldn't create connection to server.
2024-02-17 13:15:17.111 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-02-17 13:15:17.112 [info] [Error - 1:15:17 PM] Restarting server failed
2024-02-17 13:15:17.112 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```
>python -V
>Python 3.10.2

_Originally posted by @kkibria in https://github.com/microsoft/vscode-isort/issues/199#issuecomment-1950356904_

**Comment by karthiknadig** [comment]
@kkibria This looks like you have a broken python installation. This has nothing to do with the extension. Try re-installing python.
