### ISSUE TITLE
[WinError 64] The specified network name is no longer available

### ISSUE THREAD

**Issue by buzzysin** [microsoft/vscode-isort#410]
System info:
Windows 11 (Windows NT x64 10.0.22631)
VS Code version 1.88.1
ms-python.isort: 2023.10.1

This issue occurs with multiple formatters. I've tried ms-python.{autopep8, black, isort} and the same error occurs:

```py
2024-04-19 17:49:15.245 [info] Getting interpreter from ms-python.python extension for workspace <OBFUSCATED>\code-windows\robotics-grp
2024-04-19 17:49:15.247 [info] Interpreter from ms-python.python extension for <OBFUSCATED>\code-windows\robotics-grp: <OBFUSCATED>\miniconda3\python.exe
2024-04-19 17:49:15.250 [info] Server run command: <OBFUSCATED>\miniconda3\python.exe <OBFUSCATED>\.vscode\extensions\ms-python.isort-2023.13.10681007\bundled\tool\lsp_server.py
2024-04-19 17:49:15.250 [info] Server: Start requested.
2024-04-19 17:49:17.276 [info] Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "<OBFUSCATED>\miniconda3\Lib\asyncio\windows_events.py", line 461, in finish_socket_func
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<OBFUSCATED>\miniconda3\Lib\asyncio\proactor_events.py", line 793, in _loop_self_reading
    f.result()  # may raise
    ^^^^^^^^^^
  File "<OBFUSCATED>\miniconda3\Lib\asyncio\windows_events.py", line 798, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<OBFUSCATED>\miniconda3\Lib\asyncio\windows_events.py", line 465, in finish_socket_func
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] The specified network name is no longer available
```

I expect this to be an environment or a network configuration issue on my end, but I haven't narrowed it down. Disabled my VPN, tried a different wireless channel, reset my wifi adaptor.

**Comment by karthiknadig** [comment]
Are you using a File share? This is common if the file share machine is somehow blocked either by firewall or antimalware, or if the share name changed.

**Comment by buzzysin** [comment]
Hi @karthiknadig, I am afraid I am just using the Windows file system, no layers in-between, no WSL, etc.

**Comment by karthiknadig** [comment]
@buzzysin Did you update the value of any Environment variables? Did you change anything in hosts file?

**Comment by buzzysin** [comment]
@karthiknadig My hosts file is untouched and my environment is something like this:

```cmd
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\<OBFUSCATED>\AppData\Roaming
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=133225105888499757
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=LAPTOP-04JPOVGU
ComSpec=C:\WINDOWS\system32\cmd.exe
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
CUDA_PATH_V11_7=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
DriverData=C:\Windows\System32\Drivers\DriverData
EFC_5244=1
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\<OBFUSCATED>
INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
LOCALAPPDATA=C:\Users\<OBFUSCATED>\AppData\Local
LOGONSERVER=\\LAPTOP-04JPOVGU
MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic
NUMBER_OF_PROCESSORS=16
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
OneDrive=C:\Users\<OBFUSCATED>
OneDriveCommercial=C:\Users\<OBFUSCATED>
OneDriveConsumer=C:\Users\<OBFUSCATED>\OneDrive
OS=Windows_NT
Path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp;;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.2.0\;C:\Program Files\PowerShell\7\;C:\Users\<OBFUSCATED>\anaconda3\condabin;Fake:\Users\<OBFUSCATED>\anaconda3\Scripts;Fake:\Users\<OBFUSCATED>\anaconda3\Library\bin;C:\Users\<OBFUSCATED>\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\<OBFUSCATED>\AppData\Local\Programs\Python\Python311\;C:\Users\<OBFUSCATED>\AppData\Local\Microsoft\WindowsApps;C:\Users\<OBFUSCATED>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<OBFUSCATED>\latexindent\bin\windows;C:\texlive\2022\bin\win32;C:\Program Files\Nvidia GPU Computing Toolkit\CUDA\v11.7\bin;C:\Program Files\Nvidia GPU Computing Toolkit\CUDA\v11.7\libnvvp;C:\Program Files\Nvidia GPU Computing Toolkit\CUDA\v11.7\include;C:\Program Files\Nvidia GPU Computing Toolkit\CUDA\v11.7\extras\CUPTI\lib64;C:\Program Files\Nvidia GPU Computing Toolkit\CUDA\v11.7\cuda\bin;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Home
POWERSHELL_TELEMETRY_OPTOUT=1
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
PROCESSOR_LEVEL=25
PROCESSOR_REVISION=5000
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PYENV=%USERPROFILE%\.pyenv\pyenv-win\
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\<OBFUSCATED>\AppData\Local\Temp
TMP=C:\Users\<OBFUSCATED>\AppData\Local\Temp
USERDOMAIN=LAPTOP-04JPOVGU
USERDOMAIN_ROAMINGPROFILE=LAPTOP-04JPOVGU
USERNAME=<OBFUSCATED>
USERPROFILE=C:\Users\<OBFUSCATED>
windir=C:\WINDOWS
```

**Comment by karthiknadig** [comment]
@buzzysin What is the version of miniconda that you have? also does it fail if you use windows store python?

**Comment by buzzysin** [comment]
@karthiknadig 

I was using Miniconda 3 Python 3.12 version 24.1.2-0
I installed the Windows Store version of Python which fixed my issue (I think)

**Comment by karthiknadig** [comment]
@buzzysin I sort is import organizer, you will see that when you use the `Organize Import` command. It does not register as a formatter. If you want to use it as a default import organizer on save, then you need to set it like this:
```
  "[python]": {
    "editor.codeActionsOnSave": {
        "source.organizeImports.isort": "explicit"
    },
  },
```

**Comment by buzzysin** [comment]
Thanks for the help! For now I've switched to using the windows store version of python, which solved my problem.

**Comment by karthiknadig** [comment]
@buzzysin I recommend having a look at Ruff Extension (https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff). It provides `isort`, `black`, and several linters like `pylint`, `flake8` and several `flake8` plugins in a single package. It is also implemented in rust and is significantly more performant.
