### ISSUE TITLE
Formatting error unrecognized arguments: -

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-isort#64]
I am also facing the issue, without installing  `isort` into the python environment.  I am using _v2022.1.11541002_ of the extension.

```
isort --profile black --filename /Users/foo/repos/lambda-algorand-api/app.py -
CWD Formatter: /Users/foo/repos/lambda-algorand-api
[Error - 12:13:38 PM] usage: isort [-h] [-V] [--vn] [-v] [--only-modified] [--dedup-headings] [-q]
             [-d] [--overwrite-in-place] [--show-config] [--show-files] [--df]
             [-c] [--ws] [--sp SETTINGS_PATH] [--cr CONFIG_ROOT]
             [--resolve-all-configs] [--profile PROFILE] [--old-finders]
             [-j [JOBS]] [--ac] [--interactive] [--format-error FORMAT_ERROR]
             [--format-success FORMAT_SUCCESS] [--filter-files] [-s SKIP]
             [--extend-skip EXTEND_SKIP] [--sg SKIP_GLOB]
             [--extend-skip-glob EXTEND_SKIP_GLOB] [--gitignore]
             [--ext SUPPORTED_EXTENSIONS]
             [--blocked-extension BLOCKED_EXTENSIONS] [--dont-follow-links]
             [--filename FILENAME] [--allow-root] [-a ADD_IMPORTS] [--append]
             [--af] [--rm REMOVE_IMPORTS] [--float-to-top]
             [--dont-float-to-top] [--ca] [--cs] [-e] [--ff]
             [--fgw [FORCE_GRID_WRAP]] [-i INDENT]
             [--lbi LINES_BEFORE_IMPORTS] [--lai LINES_AFTER_IMPORTS]
             [--lbt LINES_BETWEEN_TYPES] [--le LINE_ENDING] [--ls] [--lss]
             [-m {GRID,VERTICAL,HANGING_INDENT,VERTICAL_HANGING_INDENT,VERTICAL_GRID,VERTICAL_GRID_GROUPED,VERTICAL_GRID_GROUPED_NO_COMMA,NOQA,VERTICAL_HANGING_INDENT_BRACKET,VERTICAL_PREFIX_FROM_MODULE_IMPORT,HANGING_INDENT_WITH_PARENTHESES,BACKSLASH_GRID,0,1,2,3,4,5,6,7,8,9,10,11}]
             [-n] [--nis] [--ot] [--dt] [--rr] [--reverse-sort]
             [--sort-order SORT_ORDER] [--sl] [--nsl SINGLE_LINE_EXCLUSIONS]
             [--tc] [--up] [-l LINE_LENGTH] [--wl WRAP_LENGTH]
             [--case-sensitive] [--remove-redundant-aliases] [--honor-noqa]
             [--treat-comment-as-code TREAT_COMMENTS_AS_CODE]
             [--treat-all-comment-as-code] [--formatter FORMATTER] [--color]
             [--ext-format EXT_FORMAT] [--star-first] [--sd DEFAULT_SECTION]
             [--only-sections] [--ds] [--fas] [--fss] [--hcss] [--srss]
             [--fass] [-t FORCE_TO_TOP] [--combine-straight-imports]
             [--nlb NO_LINES_BEFORE] [--src SRC_PATHS]
             [-b KNOWN_STANDARD_LIBRARY]
             [--extra-builtin EXTRA_STANDARD_LIBRARY]
             [-f KNOWN_FUTURE_LIBRARY] [-o KNOWN_THIRD_PARTY]
             [-p KNOWN_FIRST_PARTY] [--known-local-folder KNOWN_LOCAL_FOLDER]
             [--virtual-env VIRTUAL_ENV] [--conda-env CONDA_ENV]
             [--py {all,2,27,3,310,35,36,37,38,39,auto}]
             [files ...]
isort: error: unrecognized arguments: -
```
I sort lints just fine, but when attempting to sort imports it fails with the above error.

_Originally posted by @juls858 in https://github.com/microsoft/vscode-isort/issues/56#issuecomment-1148039831_

**Comment by juls858** [comment]
@karthiknadig  what version is this fixed in? I just updated to v2022.1.11581002 and I still see the same issue.

**Comment by karthiknadig** [comment]
@juls858 Can you share the logs? This might be something that would have to be filed on `isort` itself.

**Comment by karthiknadig** [comment]
@juls858 from the logs it looks like it is still using `2022.1.11521002` which had the bug. Try `2022.1.11581002` and reload VS Code.

**Comment by juls858** [comment]
@karthiknadig  using 2022.1.11581002 I now have a different issue:

```
isort - --filename /Users/juliusremigio/repos/lambda-algorand-api/chalicelib/algorand.py --profile black
CWD Formatter: /Users/juliusremigio/repos/lambda-algorand-api
[Error - 12:39:22 PM] usage: isort [-h] [-V] [--vn] [-v] [--only-modified] [--dedup-headings] [-q]
             [-d] [--overwrite-in-place] [--show-config] [--show-files] [--df]
             [-c] [--ws] [--sp SETTINGS_PATH] [--cr CONFIG_ROOT]
             [--resolve-all-configs] [--profile PROFILE] [--old-finders]
             [-j [JOBS]] [--ac] [--interactive] [--format-error FORMAT_ERROR]
             [--format-success FORMAT_SUCCESS] [--filter-files] [-s SKIP]
             [--extend-skip EXTEND_SKIP] [--sg SKIP_GLOB]
             [--extend-skip-glob EXTEND_SKIP_GLOB] [--gitignore]
             [--ext SUPPORTED_EXTENSIONS]
             [--blocked-extension BLOCKED_EXTENSIONS] [--dont-follow-links]
             [--filename FILENAME] [--allow-root] [-a ADD_IMPORTS] [--append]
             [--af] [--rm REMOVE_IMPORTS] [--float-to-top]
             [--dont-float-to-top] [--ca] [--cs] [-e] [--ff]
             [--fgw [FORCE_GRID_WRAP]] [-i INDENT]
             [--lbi LINES_BEFORE_IMPORTS] [--lai LINES_AFTER_IMPORTS]
             [--lbt LINES_BETWEEN_TYPES] [--le LINE_ENDING] [--ls] [--lss]
             [-m {GRID,VERTICAL,HANGING_INDENT,VERTICAL_HANGING_INDENT,VERTICAL_GRID,VERTICAL_GRID_GROUPED,VERTICAL_GRID_GROUPED_NO_COMMA,NOQA,VERTICAL_HANGING_INDENT_BRACKET,VERTICAL_PREFIX_FROM_MODULE_IMPORT,HANGING_INDENT_WITH_PARENTHESES,BACKSLASH_GRID,0,1,2,3,4,5,6,7,8,9,10,11}]
             [-n] [--nis] [--ot] [--dt] [--rr] [--reverse-sort]
             [--sort-order SORT_ORDER] [--sl] [--nsl SINGLE_LINE_EXCLUSIONS]
             [--tc] [--up] [-l LINE_LENGTH] [--wl WRAP_LENGTH]
             [--case-sensitive] [--remove-redundant-aliases] [--honor-noqa]
             [--treat-comment-as-code TREAT_COMMENTS_AS_CODE]
             [--treat-all-comment-as-code] [--formatter FORMATTER] [--color]
             [--ext-format EXT_FORMAT] [--star-first] [--sd DEFAULT_SECTION]
             [--only-sections] [--ds] [--fas] [--fss] [--hcss] [--srss]
             [--fass] [-t FORCE_TO_TOP] [--combine-straight-imports]
             [--nlb NO_LINES_BEFORE] [--src SRC_PATHS]
             [-b KNOWN_STANDARD_LIBRARY]
             [--extra-builtin EXTRA_STANDARD_LIBRARY]
             [-f KNOWN_FUTURE_LIBRARY] [-o KNOWN_THIRD_PARTY]
             [-p KNOWN_FIRST_PARTY] [--known-local-folder KNOWN_LOCAL_FOLDER]
             [--virtual-env VIRTUAL_ENV] [--conda-env CONDA_ENV]
             [--py {all,2,27,3,310,35,36,37,38,39,auto}]
             [files ...]
isort: error: unrecognized arguments: --profile black

```

**Comment by karthiknadig** [comment]
@juls858 This is really strange, the output literally lists `--profile` as one of the usable arguments. Can you file this on `isort` and see if they have anything to say about this?

Can you try with this build and see if it works? https://github.com/microsoft/vscode-isort/suites/6833301420/artifacts/263314517 you will have download the zip file extract the VSIX file from it. then use Install from VSIX option from the Extensions view to install it.

**Comment by juls858** [comment]
@karthiknadig 
```
pip list                                                                                                                                                                                                                                                                  ─╯
Package                       Version
----------------------------- ---------
appdirs                       1.4.4
appnope                       0.1.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asn1crypto                    1.4.0
attrs                         21.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
black                         19.3b0
bleach                        4.1.0
blessed                       1.19.0
bokeh                         2.4.2
botocore                      1.23.24
certifi                       2021.10.8
cffi                          1.15.0
chalice                       1.26.2
charset-normalizer            2.0.9
click                         8.0.3
cloudpickle                   2.0.0
cryptography                  3.4.8
dask                          2021.12.0
debugpy                       1.5.1
decorator                     5.1.0
defusedxml                    0.7.1
distributed                   2021.12.0
entrypoints                   0.3
fsspec                        2021.11.1
greenlet                      1.1.2
HeapDict                      1.0.1
idna                          3.3
inquirer                      2.8.0
ipykernel                     6.6.0
ipython                       7.30.1
ipython-genutils              0.2.0
ipywidgets                    7.6.5
jedi                          0.18.1
Jinja2                        3.0.3
jmespath                      0.10.0
jsonschema                    4.3.3
jupyter-client                7.1.0
jupyter-core                  4.9.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
locket                        0.2.1
MarkupSafe                    2.0.1
matplotlib-inline             0.1.3
mistune                       0.8.4
modin                         0.12.1
msgpack                       1.0.3
mypy-extensions               0.4.3
nbclient                      0.5.9
nbconvert                     6.4.0
nbformat                      5.1.3
nest-asyncio                  1.5.4
notebook                      6.4.6
numpy                         1.22.0
oscrypto                      1.2.1
packaging                     21.3
pandas                        1.3.5
pandocfilters                 1.5.0
parso                         0.8.3
partd                         1.2.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.0.0
pip                           21.2.4
prometheus-client             0.12.0
prompt-toolkit                3.0.24
psutil                        5.9.0
ptyprocess                    0.7.0
py-algorand-sdk               1.8.0
pyarrow                       5.0.0
pycparser                     2.21
pycryptodomex                 3.12.0
Pygments                      2.11.1
PyJWT                         2.3.0
PyNaCl                        1.4.0
pyOpenSSL                     20.0.1
pyparsing                     3.0.6
pyrsistent                    0.18.0
python-dateutil               2.8.2
python-editor                 1.0.4
pytz                          2021.3
PyYAML                        6.0
pyzmq                         22.3.0
readchar                      2.0.1
requests                      2.27.0
Send2Trash                    1.8.0
setuptools                    58.0.4
six                           1.16.0
snowflake-connector-python    2.7.0
snowflake-sqlalchemy          1.3.3
sortedcontainers              2.4.0
SQLAlchemy                    1.4.29
swifter                       1.0.9
tblib                         1.7.0
terminado                     0.12.1
testpath                      0.5.0
toml                          0.10.2
toolz                         0.11.2
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.1
typing_extensions             4.0.1
urllib3                       1.26.7
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.0
widgetsnbextension            3.5.2
zict                          2.0.0
```

**Comment by juls858** [comment]
@karthiknadig I did not test with the artifact. I tested with with the version you referenced.  Below are the results of testing with the artifact _v2022.1.2457079236-dev_.

```
isort - --profile black --check --filename /Users/juliusremigio/repos/lambda-algorand-api/chalicelib/algorand.py
CWD Formatter: /Users/juliusremigio/repos/lambda-algorand-api
isort - --profile black --filename /Users/juliusremigio/repos/lambda-algorand-api/chalicelib/algorand.py
CWD Formatter: /Users/juliusremigio/repos/lambda-algorand-api
[Error - 2:49:27 PM] ERROR: Filename override is intended only for stream (-) sorting.
```

The file that gets sorted gets overwritten with an empty line.

**Comment by karthiknadig** [comment]
@juls858 I am sorry that I have to ask you to do this. For some reason, I cannot locally reproduce this. Please uninstall the dev version of the extension, and install `2022.1.11581002` from market place. Lets try and see if we can minimally repro this. Basically what we are trying to do in the server is equivalent to this in terminal.

```
cat /Users/juliusremigio/repos/lambda-algorand-api/chalicelib/algorand.py | python -m isort - --profile black --filename /Users/juliusremigio/repos/lambda-algorand-api/chalicelib/algorand.py
```

To exactly repo this can you create a python file with this content `testisort.py`:

``` python
import runpy
import sys
# we only need the bundled isort
sys.path.insert(0, '/Users/foo/.vscode/extensions/ms-python.isort-2022.1.11581002/bundled/libs')

sys.argv = ["isort", "-", "--profile", "black", "--filename", r"/Users/juliusremigio/repos/lambda-algorand-api/chalicelib/algorand.py"]
runpy.run_module('isort', run_name="__main__")
```

then run this, after activating your environment:

```
cat /Users/juliusremigio/repos/lambda-algorand-api/chalicelib/algorand.py | python -m testisort.py
```

If this works right, then you should see the formatted contents of algorand.py otherwise you should see the error. It this works, and you see formatted content, then the issue might be some where else in the formatting code. Otherwise, it might be isort.

**Comment by juls858** [comment]
@karthiknadig 

The output is a property formatted in the terminal with the following line at the end:
```
/usr/local/Caskroom/miniconda/base/envs/lambda-algorand-api/bin/python: Error while finding module specification for 'testisort.py' (ModuleNotFoundError: __path__ attribute not found on 'testisort' while trying to find 'testisort.py'). Try using 'testisort' instead of 'testisort.py' as the module name.
```

Using extension:
```
isort - --filename /Users/foo/repos/lambda-algorand-api/chalicelib/algorand.py --profile black
CWD Formatter: /Users/foo/repos/lambda-algorand-api
[Error - 3:37:16 PM] usage: isort [-h] [-V] [--vn] [-v] [--only-modified] [--dedup-headings] [-q]
             [-d] [--overwrite-in-place] [--show-config] [--show-files] [--df]
             [-c] [--ws] [--sp SETTINGS_PATH] [--cr CONFIG_ROOT]
             [--resolve-all-configs] [--profile PROFILE] [--old-finders]
             [-j [JOBS]] [--ac] [--interactive] [--format-error FORMAT_ERROR]
             [--format-success FORMAT_SUCCESS] [--filter-files] [-s SKIP]
             [--extend-skip EXTEND_SKIP] [--sg SKIP_GLOB]
             [--extend-skip-glob EXTEND_SKIP_GLOB] [--gitignore]
             [--ext SUPPORTED_EXTENSIONS]
             [--blocked-extension BLOCKED_EXTENSIONS] [--dont-follow-links]
             [--filename FILENAME] [--allow-root] [-a ADD_IMPORTS] [--append]
             [--af] [--rm REMOVE_IMPORTS] [--float-to-top]
             [--dont-float-to-top] [--ca] [--cs] [-e] [--ff]
             [--fgw [FORCE_GRID_WRAP]] [-i INDENT]
             [--lbi LINES_BEFORE_IMPORTS] [--lai LINES_AFTER_IMPORTS]
             [--lbt LINES_BETWEEN_TYPES] [--le LINE_ENDING] [--ls] [--lss]
             [-m {GRID,VERTICAL,HANGING_INDENT,VERTICAL_HANGING_INDENT,VERTICAL_GRID,VERTICAL_GRID_GROUPED,VERTICAL_GRID_GROUPED_NO_COMMA,NOQA,VERTICAL_HANGING_INDENT_BRACKET,VERTICAL_PREFIX_FROM_MODULE_IMPORT,HANGING_INDENT_WITH_PARENTHESES,BACKSLASH_GRID,0,1,2,3,4,5,6,7,8,9,10,11}]
             [-n] [--nis] [--ot] [--dt] [--rr] [--reverse-sort]
             [--sort-order SORT_ORDER] [--sl] [--nsl SINGLE_LINE_EXCLUSIONS]
             [--tc] [--up] [-l LINE_LENGTH] [--wl WRAP_LENGTH]
             [--case-sensitive] [--remove-redundant-aliases] [--honor-noqa]
             [--treat-comment-as-code TREAT_COMMENTS_AS_CODE]
             [--treat-all-comment-as-code] [--formatter FORMATTER] [--color]
             [--ext-format EXT_FORMAT] [--star-first] [--sd DEFAULT_SECTION]
             [--only-sections] [--ds] [--fas] [--fss] [--hcss] [--srss]
             [--fass] [-t FORCE_TO_TOP] [--combine-straight-imports]
             [--nlb NO_LINES_BEFORE] [--src SRC_PATHS]
             [-b KNOWN_STANDARD_LIBRARY]
             [--extra-builtin EXTRA_STANDARD_LIBRARY]
             [-f KNOWN_FUTURE_LIBRARY] [-o KNOWN_THIRD_PARTY]
             [-p KNOWN_FIRST_PARTY] [--known-local-folder KNOWN_LOCAL_FOLDER]
             [--virtual-env VIRTUAL_ENV] [--conda-env CONDA_ENV]
             [--py {all,2,27,3,310,35,36,37,38,39,auto}]
             [files ...]
isort: error: unrecognized arguments: --profile black

```

**Comment by juls858** [comment]
not sure if this helps:
```
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z (3 wks ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0
```

**Comment by juls858** [comment]
I recreated my python environment and tried again. Looks like I am required to install ISORT package in my local environment.

```
isort - --filename /Users/foo/repos/lambda-algorand-api/chalicelib/algorand.py --profile black
CWD Formatter: /Users/foo/repos/lambda-algorand-api
[Error - 3:56:21 PM] Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/lambda-algorand-api/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Caskroom/miniconda/base/envs/lambda-algorand-api/lib/python3.9/runpy.py", line 141, in _get_module_details
    raise error("No module named %s" % mod_name)
ImportError: No module named isort.__main__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/foo/.vscode/extensions/ms-python.isort-2022.1.11581002/bundled/formatter/format_server.py", line 143, in _run
    result = utils.run_module(
  File "/Users/foo/.vscode/extensions/ms-python.isort-2022.1.11581002/bundled/formatter/utils.py", line 177, in run_module
    return _run_module(module, argv, use_stdin, source)
  File "/Users/foo/.vscode/extensions/ms-python.isort-2022.1.11581002/bundled/formatter/utils.py", line 162, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "/usr/local/Caskroom/miniconda/base/envs/lambda-algorand-api/lib/python3.9/runpy.py", line 206, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/local/Caskroom/miniconda/base/envs/lambda-algorand-api/lib/python3.9/runpy.py", line 151, in _get_module_details
    raise error(("%s; %r is a package and cannot " +
ImportError: No module named isort.__main__; 'isort' is a package and cannot be directly executed

isort - --filename /Users/foo/repos/lambda-algorand-api/chalicelib/algorand.py --profile black
CWD Formatter: /Users/foo/repos/lambda-algorand-api
[Error - 3:57:12 PM] usage: isort [-h] [-V] [--vn] [-v] [--only-modified] [--dedup-headings] [-q]
             [-d] [--overwrite-in-place] [--show-config] [--show-files] [--df]
             [-c] [--ws] [--sp SETTINGS_PATH] [--cr CONFIG_ROOT]
             [--resolve-all-configs] [--profile PROFILE] [--old-finders]
             [-j [JOBS]] [--ac] [--interactive] [--format-error FORMAT_ERROR]
             [--format-success FORMAT_SUCCESS] [--filter-files] [-s SKIP]
             [--extend-skip EXTEND_SKIP] [--sg SKIP_GLOB]
             [--extend-skip-glob EXTEND_SKIP_GLOB] [--gitignore]
             [--ext SUPPORTED_EXTENSIONS]
             [--blocked-extension BLOCKED_EXTENSIONS] [--dont-follow-links]
             [--filename FILENAME] [--allow-root] [-a ADD_IMPORTS] [--append]
             [--af] [--rm REMOVE_IMPORTS] [--float-to-top]
             [--dont-float-to-top] [--ca] [--cs] [-e] [--ff]
             [--fgw [FORCE_GRID_WRAP]] [-i INDENT]
             [--lbi LINES_BEFORE_IMPORTS] [--lai LINES_AFTER_IMPORTS]
             [--lbt LINES_BETWEEN_TYPES] [--le LINE_ENDING] [--ls] [--lss]
             [-m {GRID,VERTICAL,HANGING_INDENT,VERTICAL_HANGING_INDENT,VERTICAL_GRID,VERTICAL_GRID_GROUPED,VERTICAL_GRID_GROUPED_NO_COMMA,NOQA,VERTICAL_HANGING_INDENT_BRACKET,VERTICAL_PREFIX_FROM_MODULE_IMPORT,HANGING_INDENT_WITH_PARENTHESES,BACKSLASH_GRID,0,1,2,3,4,5,6,7,8,9,10,11}]
             [-n] [--nis] [--ot] [--dt] [--rr] [--reverse-sort]
             [--sort-order SORT_ORDER] [--sl] [--nsl SINGLE_LINE_EXCLUSIONS]
             [--tc] [--up] [-l LINE_LENGTH] [--wl WRAP_LENGTH]
             [--case-sensitive] [--remove-redundant-aliases] [--honor-noqa]
             [--treat-comment-as-code TREAT_COMMENTS_AS_CODE]
             [--treat-all-comment-as-code] [--formatter FORMATTER] [--color]
             [--ext-format EXT_FORMAT] [--star-first] [--sd DEFAULT_SECTION]
             [--only-sections] [--ds] [--fas] [--fss] [--hcss] [--srss]
             [--fass] [-t FORCE_TO_TOP] [--combine-straight-imports]
             [--nlb NO_LINES_BEFORE] [--src SRC_PATHS]
             [-b KNOWN_STANDARD_LIBRARY]
             [--extra-builtin EXTRA_STANDARD_LIBRARY]
             [-f KNOWN_FUTURE_LIBRARY] [-o KNOWN_THIRD_PARTY]
             [-p KNOWN_FIRST_PARTY] [--known-local-folder KNOWN_LOCAL_FOLDER]
             [--virtual-env VIRTUAL_ENV] [--conda-env CONDA_ENV]
             [--py {all,2,27,3,310,35,36,37,38,39,auto}]
             [files ...]
isort: error: unrecognized arguments: --profile black
```

**Comment by karthiknadig** [comment]
@juls858 Can you share your entire settings file?

**Comment by karthiknadig** [comment]
@juls858 I think i see the problem, in your settings can you change this ``"args": ["--profile black"],``` to
```
"args": ["--profile", "black"],
```

**Comment by juls858** [comment]
@karthiknadig  thank you that fixed it!

**Comment by karthiknadig** [comment]
Phew!!! Sorry I did not notice it earlier.
