### ISSUE TITLE
Warnings in Developer Tools

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-isort#79]
```
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'uri')
    at u (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:70138)
    at l (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:70336)
    at t.restartFormatServer (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:70922)
    at f (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:302174)
    at c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:302325 (at console.<anonymous> (c:\Users\brcan\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:93517))
```

```
  ERR Cannot read properties of undefined (reading 'uri'): TypeError: Cannot read properties of undefined (reading 'uri')
    at u (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:70138)
    at l (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:70336)
    at t.restartFormatServer (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:70922)
    at f (c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:302174)
    at c:\Users\brcan\.vscode-insiders\extensions\ms-python.isort-2022.3.11671003\dist\extension.js:1:302325
```

**Comment by karthiknadig** [comment]
```
  ERR Cannot read properties of null (reading 'map'): TypeError: Cannot read properties of null (reading 'map')
    at asDiagnostics (c:\GIT\formatters\vscode-isort\dist\webpack:\isort\node_modules\vscode-languageclient\lib\common\protocolConverter.js:34:1)
    at Object.asCodeAction (c:\GIT\formatters\vscode-isort\dist\webpack:\isort\node_modules\vscode-languageclient\lib\common\protocolConverter.js:598:1)
    at c:\GIT\formatters\vscode-isort\dist\webpack:\isort\node_modules\vscode-languageclient\lib\common\client.js:1226:1
    at A.provideCodeActions (c:\Users\Karthik Nadig\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:42766)
```
This seems to occur due to us returning code actions even when it is not needed. In `def code_action_organize_imports(params: lsp.CodeActionParams)` in `server.py` we return both organize and quick fix code actions in all cases. We should only be retrning quickfix if one is needed. We should not be returning the organize code action when providing a quickfix.

**Comment by karthiknadig** [comment]
This error should not occur any more. Please re-open if it does again.
